### ISSUE TITLE
When a field has no description (description=None) initialization fails

### ISSUE THREAD

**Issue by pbauer** [zopefoundation/zope.schema#69]
The recent changes broke the Plone-biuld (e.g. https://jenkins.plone.org/view/PLIPs/job/plip-py3/707)

```
Traceback (most recent call last):
  File "/home/jenkins/workspace/plip-py3/src/plone.supermodel/plone/supermodel/parser.py", line 72, in parse
    return _parse(source, policy)
  File "/home/jenkins/workspace/plip-py3/src/plone.supermodel/plone/supermodel/parser.py", line 161, in _parse
    baseFields
  File "/home/jenkins/workspace/plip-py3/src/plone.supermodel/plone/supermodel/parser.py", line 122, in readField
    field = handler.read(fieldElement)
  File "/home/jenkins/workspace/plip-py3/src/plone.supermodel/plone/supermodel/exportimport.py", line 136, in read
    field_instance = self._constructField(attributes)
  File "/home/jenkins/workspace/plip-py3/src/plone.supermodel/plone/supermodel/exportimport.py", line 81, in _constructField
    return self.klass(**attributes)
  File "/home/jenkins/workspace/plip-py3/src/zope.schema/src/zope/schema/_bootstrapfields.py", line 494, in __init__
    super(Text, self).__init__(*args, **kw)
  File "/home/jenkins/workspace/plip-py3/src/zope.schema/src/zope/schema/_bootstrapfields.py", line 476, in __init__
    super(MinMaxLen, self).__init__(**kw)
  File "/home/jenkins/workspace/plip-py3/src/zope.schema/src/zope/schema/_bootstrapfields.py", line 244, in __init__
    doc_description = '\n'.join(_DocStringHelpers.docstring_to_lines(description)[:-1])
  File "/home/jenkins/workspace/plip-py3/src/zope.schema/src/zope/schema/_bootstrapfields.py", line 133, in docstring_to_lines
    lines = docstring.expandtabs().splitlines()
plone.supermodel.parser.SupermodelParseError: 'NoneType' object has no attribute 'expandtabs'
```

**Comment by pbauer** [comment]
Thanks!
